name: generate monkeytype readme svg

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  download-svg:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download SVG
        run: |
          mkdir -p public
          curl -o public/monkeytype.svg https://monkeytype-readme.com/generate-svg/francisdavid/dark

      - name: Commit and push to branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b monkeytype-readme || git checkout monkeytype-readme
          git add public/monkeytype.svg
          git commit -m "update monkeytype stats" || echo "No changes to commit"
          git push origin monkeytype-readme --force
